CLI search fails trying to format create time
gracedb search GRB --columns=created
ERROR: 'unicode' object has no attribute 'isoformat'

Bug introduced in commit 3b31d9d3af117ca40769eb786b13a0b320764e5a
    changed created time in eventToDict to UTC